##
# plant_1
##
- name: plant_1_soil_moisture
  state: >
    {{states("sensor.soilcontrol_grow_flower_care_mini_1_moisture") | float }}
  unit_of_measurement: "%"
  icon: mdi:water-percent
- name: plant_1_temperature
  state: >
    {{states("sensor.soilcontrol_grow_flower_care_mini_1_temperature") | float }}
  unit_of_measurement: "%"
  icon: mdi:temperature-celsius
- name: plant_1_soil_conductivity
  state: >
    {{states("sensor.soilcontrol_grow_flower_care_mini_1_soil_conductivity") | float }}
  unit_of_measurement: "µS/cm"
  icon: mdi:flash-triangle-outline

##
# plant_2
##
- name: plant_2_soil_moisture
  state: >
    {{states("sensor.soilcontrol_grow_flower_care_mini_2_moisture") | float }}
  unit_of_measurement: "%"
  icon: mdi:water-percent
- name: plant_2_temperature
  state: >
    {{states("sensor.soilcontrol_grow_flower_care_mini_2_temperature") | float }}
  unit_of_measurement: "%"
  icon: mdi:temperature-celsius
- name: plant_2_soil_conductivity
  state: >
    {{states("sensor.soilcontrol_grow_flower_care_mini_2_soil_conductivity") | float }}
  unit_of_measurement: "µS/cm"
  icon: mdi:flash-triangle-outline

##
# plant_3
##
- name: plant_3_soil_moisture
  state: >
    {{states("sensor.soilcontrol_grow_flower_care_mini_3_moisture") | float }}
  unit_of_measurement: "%"
  icon: mdi:water-percent
- name: plant_3_temperature
  state: >
    {{states("sensor.soilcontrol_grow_flower_care_mini_3_temperature") | float }}
  unit_of_measurement: "%"
  icon: mdi:temperature-celsius
- name: plant_3_soil_conductivity
  state: >
    {{states("sensor.soilcontrol_grow_flower_care_mini_3_soil_conductivity") | float }}
  unit_of_measurement: "µS/cm"
  icon: mdi:flash-triangle-outline
