- name: area_1_exhaust_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_1_is_exhaust_dimmable") == 'on' and states('light.pkecblue_light_0') == "on"%}{{(states.light.pkecblue_light_0.attributes.brightness  * 100 / 255 | float) | round(0)}}
    {% elif states("binary_sensor.area_1_exhaust_state") == 'on' and states('light.pkecblue_light_0') == "off"%}{{0}}   
    {% elif states("binary_sensor.area_1_exhaust_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_1_exhaust_state") == 'off' %}{{0}}
    {% else %}{{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_1_light_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_1_is_light_dimmable") == 'on' and states('light.growlightdimmer_light_0') == "on"%}{{ (states.light.growlightdimmer_light_0.attributes.brightness  * 100 / 255 | float) | round(0)}}
    {% elif states("binary_sensor.area_1_light_state") == 'on' and states('light.growlightdimmer_light_0') == "off"%}{{0}}
    {% elif states("binary_sensor.area_1_light_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_1_light_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_1_ventilation_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_1_is_ventilation_dimmable") == 'on' and true == false %}{{states.fan.aircontrol_grow_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_1_ventilation_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_1_ventilation_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_1_heater_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_1_is_heater_dimmable") == 'on' and true == false %}{{states.fan.aircontrol_grow_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_1_heater_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_1_heater_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_1_humidifier_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_1_is_humidifier_dimmable") == 'on' and true == false %}{{states.fan.aircontrol_grow_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_1_humidifier_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_1_humidifier_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_1_dehumidifier_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_1_is_dehumidifier_dimmable") == 'on' and true == false %}{{states.fan.aircontrol_grow_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_1_dehumidifier_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_1_dehumidifier_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_2_exhaust_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_2_is_exhaust_dimmable") == 'on' and true == false %}{{states.fan.aircontrol_propagator_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_2_exhaust_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_2_exhaust_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_2_light_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_2_is_light_dimmable") == 'on' and true == false %}{{states.fan.aircontrol_grow_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_2_light_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_2_light_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_2_ventilation_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_2_is_ventilation_dimmable") == 'on' and true == false%}{{states.fan.aircontrol_grow_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_2_ventilation_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_2_ventilation_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_2_heater_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_2_is_heater_dimmable") == 'on' and true == false%}{{states.fan.aircontrol_grow_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_2_heater_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_2_heater_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_2_humidifier_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_2_is_humidifier_dimmable") == 'on' and true == false%}{{states.fan.aircontrol_grow_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_2_humidifier_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_2_humidifier_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
- name: area_2_dehumidifier_percentage
  state: > #to be configured
    {% if states("binary_sensor.area_2_is_dehumidifier_dimmable") == 'on' and true == false %}{{states.fan.aircontrol_grow_ruck_ec.attributes.percentage}}
    {% elif states("binary_sensor.area_2_dehumidifier_state") == 'on' %}{{100}}
    {% elif states("binary_sensor.area_2_dehumidifier_state") == 'off' %}{{0}}
    {% else %} {{0}}
    {% endif %}
  unit_of_measurement: "%"
