# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

homeassistant: !include homeassistant.yaml
automation: !include_dir_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb: !include influxdb.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml
input_select: !include input_select.yaml
sensor: !include sensor.yaml
schedule: !include schedule.yaml
