- platform: template
  sensors:
    days_since_grow_start:
      friendly_name: "Days_Since_Grow_Start"
      icon_template: mdi:calendar
      value_template: "{{ ((as_timestamp(now()) - (states.input_datetime.grow_startdate.attributes.timestamp)) | int /60/1440) | round(0) }}"
      unit_of_measurement: Tage
    current_week_of_grow:
      friendly_name: "Current_Week_of_Grow"
      icon_template: mdi:calendar
      value_template: "{{ ((as_timestamp(now()) - (states.input_datetime.grow_startdate.attributes.timestamp)) | int /60/1440//7 +1)  | round(0) }}"
      unit_of_measurement: Weeks
    plant1_days_until_flower:
      friendly_name: "plant1_days_until_flower"
      icon_template: mdi:calendar
      value_template: >-
        {% set start_date = as_timestamp(states('states.input_datetime.grow_startdate.attributes.timestamp')) %}
        {% set veg_days = states('input_number.plant1_daysofveg') | int %}
        {% set today = as_timestamp(now()) %}
        {% set remaining_days = start_date + (veg_days * 86400) - today %}
        {{ remaining_days }}
      unit_of_measurement: Tage
    plant1_days_until_drying:
      friendly_name: "plant1_days_until_drying"
      icon_template: mdi:calendar
      value_template: "{{ ((as_timestamp(now()) - (states.input_datetime.grow_startdate.attributes.timestamp)) | int /60/1440)  | round(0) }}"
      unit_of_measurement: Tage
    plant1_days_until_comsumption:
      friendly_name: "plant1_days_until_comsumption"
      icon_template: mdi:calendar
      value_template: "{{ ((as_timestamp(now()) - (states.input_datetime.grow_startdate.attributes.timestamp)) | int /60/1440)  | round(0) }}"
      unit_of_measurement: Tage
