esphome:
  #to be configured
  name: airmonitoring-YourAreaName
  #to be configured
  friendly_name: AirMonitoring-YourAreaName

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "mVZe3zUYEQbGcdX0k8zDWqWWBoMylTDSmI+JUcQ4aqg="

ota:
  password: "5061c4844b0ff33c415e3b18e52c937e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    #to be configured
    ssid: "Airmonitoring-YourAreaName"
    password: "3RGnyLbTn2bN"

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

  #to be configured for your sensors
sensor:
  #- platform: hdc1080
  #  address: 0x40
  #  i2c_id: bus_a
  #  temperature:
  #    name: "Temperature"
  #    unit_of_measurement: "°C"
  #    id: temperature
  #  humidity:
  #    name: "Humidity"
  #    id: humidity
  #  update_interval: 15s

  - platform: sht3xd
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      unit_of_measurement: "°C"
      id: temperature
    humidity:
      name: "Humidity"
      id: humidity
      unit_of_measurement: "%"
    update_interval: 15s


  - platform: ens160
    eco2:
      name: "eCO2"
      id: co2
    tvoc:
      name: "Total Volatile Organic Compounds"
    aqi:
      name: "Air Quality Index"
    update_interval: 30s
    i2c_id: bus_a
    address: 0x53
    compensation:
      temperature: temperature
      humidity: humidity