area_1_automation_humidifier_interval_duration:  
  name: Bereich 1 Automation Luftbefeuchter Intervall Dauer
  initial: 5
  min: 0
  max: 30
  unit_of_measurement: seconds

area_1_automation_dehumidifier_interval_duration:
  name: Bereich 1 Automation Luftentfeuchter Intervall Dauer
  initial: 10
  min: 0
  max: 30
  unit_of_measurement: seconds

area_1_automation_heater_interval_duration:
  name: Bereich 1 Automation Heizung Intervall Dauer
  initial: 5
  min: 0
  max: 30
  unit_of_measurement: seconds

area_1_automation_exhaust_interval_duration:
  name: Bereich 1 Automation Abluft Intervall Dauer
  initial: 5
  min: 0
  max: 30
  unit_of_measurement: seconds

area_1_automation_ventilation_interval_duration:
  name: Bereich 1 Automation Umluft Intervall Dauer
  initial: 60
  min: 0
  max: 600
  unit_of_measurement: seconds
