id: backup
alias: "Backup"
initial_state: true
description: ""
trigger:
  - platform: state
    entity_id:
      - schedule.backup_schedule
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - input_button.backup_manual
condition: []
action:
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: trigger
