id: light_schedule_veg_end
alias: light_schedule_veg_end
description: ""
initial_state: false
trigger:
  - platform: state
    entity_id:
      - schedule.veg_lighplan
    from: "on"
    to: "off"
condition:
  - condition: state
    entity_id: input_select.plant1_stage
    state: Veg
action:
  - type: turn_off
    device_id: 198f8f298745cd58abb591f830b94d88
    entity_id: e3fa0f71436ff94cc94d04541d337eaa
    domain: switch
mode: single
