- icon: mdi:fan
  name: area_1_ventilation_state
  state: > #to be configured
    {{states('switch.grow_ventilation_switch_0')}}
- icon: mdi:air-conditioner
  name: area_1_exhaust_state
  state: > #to be configured
    {{states('switch.grow_exhaust_switch_0')}}
- icon: mdi:radiator
  name: area_1_heater_state
  state: > #to be configured
    {{states('switch.grow_heater_switch_0')}}
- icon: mdi:air-humidifier
  name: area_1_humidifier_state
  state: > #to be configured
    {{states('switch.grow_humidifier_switch_0')}}
- icon: mdi:air-humidifier-off
  name: area_1_dehumidifier_state
  state: > #to be configured
    {{states('switch.grow_dehumidifier_switch_0')}}
- icon: mdi:lightbulb
  name: area_1_light_state
  state: > #to be configured
    {{states('switch.grow_light_switch_0')}}
- icon: mdi:temperature-celsius
  name: multiple_sensors_area_1_temperature_air
  state: false
- icon: mdi:temperature-celsius
  name: multiple_sensors_area_1_temperature_leaf
  state: false
- icon: mdi:water-percent
  name: multiple_sensors_area_1_humidity
  state: false
- icon: mdi:molecule-co2
  name: multiple_sensors_area_1_co2
  state: false
- icon: mdi:fan
  name: area_2_ventilation_state
  state: > #to be configured
    {{states('switch.grow_ventilation_switch_0')}}
- icon: mdi:air-conditioner
  name: area_2_exhaust_state
  state: > #to be configured
    {{states('switch.propagator_exhaust_switch_0')}}
- icon: mdi:radiator
  name: area_2_heater_state
  state: > #to be configured
    {{states('switch.grow_heater_switch_0')}}
- icon: mdi:air-humidifier
  name: area_2_humidifier_state
  state: > #to be configured
    {{states('switch.grow_humidifier_switch_0')}}
- icon: mdi:air-humidifier-off
  name: area_2_dehumidifier_state
  state: > #to be configured
    {{states('switch.grow_dehumidifier_switch_0')}}
- icon: mdi:lightbulb
  name: area_2_light_state
  state: > #to be configured
    {{states('switch.propagator_light_switch_0')}}
- icon: mdi:temperature-celsius
  name: multiple_sensors_area_2_temperature_air
  state: false
- icon: mdi:temperature-celsius
  name: multiple_sensors_area_2_temperature_leaf
  state: false
- icon: mdi:water-percent
  name: multiple_sensors_area_2_humidity
  state: false
- icon: mdi:molecule-co2
  name: multiple_sensors_area_2_co2
  state: false
