blueprint:
  name: GrowBot automatic humidity control
  description: ---- DESCRIPTION HERE -----
  domain: automation
  author: GrowBot Open Source
  input:
    humidity_sensor:
      name: humidity_sensor
      selector:
        entity:
          include_entities:
            - sensor.airmonitoring_grow_humidity
    humidity_min_value:
      name: humidity_min_value
      selector:
        entity:
          include_entities:
            - sensor.humidity_min_seed
            - sensor.humidity_min_veg
            - sensor.humidity_min_flower
            - sensor.humidity_min_dry
    humidity_target_value:
      name: humidity_target_value
      selector:
        entity:
          include_entities:
            - input_number.target_humidity_seed
            - input_number.target_humidity_veg
            - input_number.target_humidity_flower
            - input_number.target_humidity_dry
    humidity_max_value:
      name: humidity_max_value
      selector:
        entity:
          include_entities:
            - sensor.humidity_max_seed
            - sensor.humidity_max_veg
            - sensor.humidity_max_flower
            - sensor.humidity_max_dry
    grow_stage_inputselector:
      name: grow_stage_inputselector
      selector:
        entity:
          include_entities:
            - input_select.plant1_stage
    grow_stage_value:
      name: grow_stage_value
      selector:
        select:
          options:
            - Seed
            - Veg
            - Flower
            - Dry
          mode: dropdown
    target_script_humidifier:
      name: target_script_humidifier
      selector:
        entity:
          include_entities:
            - script.humidifier_control
    target_script_dehumidifier:
      name: target_script_dehumidifier
      selector:
        entity:
          include_entities:
            - script.airflowfan_control

mode: single

trigger:
  - platform: numeric_state
    entity_id: !input humidity_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
    above: !input humidity_max_value
    id: "high"
  - platform: numeric_state
    entity_id: !input humidity_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
    below: !input humidity_min_value
    id: "low"
  - platform: template
    value_template: "{{ states('sensor.airmonitoring_grow_humidity') | float == states('input_number.target_humidity_flower') | float }}"
    id: "good"

condition:
  - condition: state
    entity_id: !input grow_stage_inputselector
    state: !input grow_stage_value
    for:
      hours: 0
      minutes: 2
      seconds: 0
action:
  - if:
      - condition: trigger
        id:
          - "low"
    then:
      - service: !input target_script_humidifier
        data:
          state: true
  - if:
      - condition: trigger
        id:
          - "high"
    then:
      - service: !input target_script_dehumidifier
        data:
          state: true
  - if:
      - condition: trigger
        id:
          - "good"
    then:
      - service: !input target_script_humidifier
        data:
          state: false
      - service: !input target_script_dehumidifier
        data:
          state: false
