blueprint:
  name: GrowBot automatic air condition control 
  description: >
    Die Datei auto_air_control.yaml ist Teil des GrowBot Open Source-Projekts und dient zur automatischen Steuerung der Luftbedingungen in Ihrer Grow-Umgebung. Bitte folgen Sie der Anleitung und implementieren Sie die notwendigen Sensoren und Trigger in Ihrem Home Assistant-System.
  domain: automation
  author: GrowBot Open Source
  input:
    air_control_trigger_sensor:
      name: Template Sensor des Bereichs zur Steuerung der Luftbedingungen
      description: Wählen Sie den Sensor aus. Dieser Sensor wird verwendet, um den aktuellen Zustand des Bereichs zu überwachen.
      selector:
        entity:
          domain: sensor
          include_entities:
          # Add your area job sensor entities here
            - sensor.area_1_air_control_job
    target_script_humidifier_on:
      name: Luftbefeuchter Skript zum Einschalten
      description: Das Skript, das den Luftbefeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your humidifier script entities here
            - script.device_control_humidifier_on
    target_script_humidifier_off:
      name: Luftbefeuchter Skript zum Ausschalten
      description: Das Skript, das den Luftbefeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your humidifier script entities here
            - script.device_control_humidifier_off
    target_script_dehumidifier_on:
      name: Luftentfeuchter Skript zum Einschalten
      description: Das Skript, das den Luftentfeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your dehumidifier script entities here
            - script.device_control_airflowfan_on
    target_script_dehumidifier_off:
      name: Luftentfeuchter Skript zum Ausschalten
      description: Das Skript, das den Luftentfeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your dehumidifier script entities here
            - script.device_control_airflowfan_off
    target_script_heater_on:
      name: Heizung Skript zum Einschalten
      description: Das Skript, das die Heizung steuert
      selector:
        entity:
          include_entities:
          # Add your heater script entities here
            - script.device_control_heater_on
    target_script_heater_off:
      name: Heizung Skript zum Ausschalten
      description: Das Skript, das die Heizung steuert
      selector:
        entity:
          include_entities:
          # Add your heater script entities here
            - script.device_control_heater_off
    target_script_ac_on:
      name: Klima / Abluft Skript zum Einschalten
      description: Das Skript, das die Klima / Abluft steuert
      selector:
        entity:
          include_entities:
          # Add your ac script entities here
            - script.device_control_ac_on
    target_script_ac_off:
      name: Klima / Abluft Skript zum Ausschalten
      description: Das Skript, das die Klima / Abluft steuert
      selector:
        entity:
          include_entities:
          # Add your ac script entities here
            - script.device_control_ac_off
    air_control_helper_script:
      name: Helferskript zur Speicherung des letztes Jobs
      description: Das Skript, das den letzten Job speichert
      selector:
        entity:
          include_entities:
          # Add your helper script entities here
            - script.air_control_helper_script

mode: single

trigger:
# 
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'heater_on'
    id: heater_on
# 
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'ac_on'
    id: ac_on
#
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'humidifier_on'
    id: humidifier_on
#
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'dehumidifier_on'
    id: dehumidifier_on
# 
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'heater_and_humidifier_on'
    id: heater_and_humidifier_on
# 
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'heater_and_dehumidifier_on'
    id: heater_and_dehumidifier_on
#
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'ac_and_humidifier_on'
    id: ac_and_humidifier_on
#
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'ac_and_dehumidifier_on'
    id: ac_and_dehumidifier_on
# 
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'heater_off'
    id: heater_off
# 
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'ac_off'
    id: ac_off
#
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'humidifier_off'
    id: humidifier_off
#
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'dehumidifier_off'
    id: dehumidifier_off
# 
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'heater_and_humidifier_off'
    id: heater_and_humidifier_off
# 
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'heater_and_dehumidifier_off'
    id: heater_and_dehumidifier_off
#
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'ac_and_humidifier_off'
    id: ac_and_humidifier_off
#
  - platform: state
    entity_id: !input air_control_trigger_sensor
    to:  'ac_and_dehumidifier_off'
    id: ac_and_dehumidifier_off

action:
  - if:
      - condition: trigger
        id:
          - "heater_on"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_on
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "ac_on"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_on
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "humidifier_on"
    then:
      - service: !input target_script_humidifier_on
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script

  - if:
      - condition: trigger
        id:
          - "dehumidifier_on"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_on
      - service: !input target_script_ac_off
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "heater_and_humidifier_on"
    then:
      - service: !input target_script_humidifier_on
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_on
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "heater_and_dehumidifier_on"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_on
      - service: !input target_script_ac_off
      - service: !input target_script_heater_on
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "ac_and_humidifier_on"
    then:
      - service: !input target_script_humidifier_on
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_on
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "ac_and_dehumidifier_on"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_on
      - service: !input target_script_ac_on
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "heater_off"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "ac_off"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "humidifier_off"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "dehumidifier_off"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "heater_and_humidifier_off"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "heater_and_dehumidifier_off"
    then:
      - service: !input target_script_humidifier_on
      - service: !input target_script_dehumidifier_on
      - service: !input target_script_ac_on
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "ac_and_humidifier_off"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script
  - if:
      - condition: trigger
        id:
          - "ac_and_dehumidifier_off"
    then:
      - service: !input target_script_humidifier_off
      - service: !input target_script_dehumidifier_off
      - service: !input target_script_ac_off
      - service: !input target_script_heater_off
      - service: !input air_control_helper_script

