blueprint:
  name: GrowBot automatic temperature control 
  description: >
    Die Datei auto_temperature.yaml ist Teil des GrowBot Open Source-Projekts und dient zur automatischen Steuerung der Temperatur in Ihrer Grow-Umgebung.   
  domain: automation
  author: GrowBot Open Source
  input:
    temperature_sensor:
      name: Temperatursensor
      description: Der Sensor für die aktuelle Temperatur
      selector:
        entity:
          include_entities:
          # Add your temperature sensor entities here
            - sensor.airmonitoring_grow_temperature
    temperature_trigger_low_adjustment:
      name: Min-Temperatur Trigger
      description: Der Trigger für die minimale Temperatur
      selector:
        entity:
          domain: binary_sensor
          include_entities:
          # Add your temperature min trigger entities here
            - binary_sensor.temperature_low_adjustment_seed
            - binary_sensor.temperature_low_adjustment_veg
            - binary_sensor.temperature_low_adjustment_flower
            - binary_sensor.temperature_low_adjustment_dry 
    temperature_trigger_low_fixed:
      name: Min-Temperatur Trigger Fixiert
      description: Der Trigger für die minimale Temperatur (fixiert)
      selector:
        entity:
          domain: binary_sensor
          include_entities:
          # Add your temperature min trigger entities here
            - binary_sensor.temperature_low_fixed_seed
            - binary_sensor.temperature_low_fixed_veg
            - binary_sensor.temperature_low_fixed_flower
            - binary_sensor.temperature_low_fixed_dry 
    temperature_trigger_high_adjustment:
      name: Max-Temperatur Trigger
      description: Der Trigger für die maximale Temperatur
      selector:
        entity:
          domain: binary_sensor
          include_entities:
          # Add your temperature max trigger entities here
            - binary_sensor.temperature_high_adjustment_seed
            - binary_sensor.temperature_high_adjustment_veg
            - binary_sensor.temperature_high_adjustment_flower
            - binary_sensor.temperature_high_adjustment_dry 
    temperature_trigger_high_fixed:
      name: Max-Temperatur Trigger fixiert
      description: Der Trigger für die maximale Temperatur (fixiert)
      selector:
        entity:
          domain: binary_sensor
          include_entities:
          # Add your temperature max trigger entities here
            - binary_sensor.temperature_high_fixed_seed
            - binary_sensor.temperature_high_fixed_veg
            - binary_sensor.temperature_high_fixed_flower
            - binary_sensor.temperature_high_fixed_dry 
    grow_stage_inputselector:
      name: Pflanzenstadiums Auswahl
      description: Der Input-Selektor für das Wachstumsstadium
      selector:
        entity:
          include_entities:
          # Add your grow stage input selector entities here
            - input_select.plant1_stage
    grow_stage_value:
      name: Pflanzenstadiums Wert
      description: Der Wert für das Wachstumsstadium
      selector:
        select:
          options:
          # Add your grow stage values here
            - Seed
            - Veg
            - Flower
            - Dry
          mode: dropdown
#    target_script_heater_on:
#      name: Heizung Skript zum Einschalten
#      description: Das Skript, das die Heizung steuert
#      selector:
#        entity:
#          include_entities:
#          # Add your heater script entities here
#            - script.device_control_heater_on
#    target_script_heater_off:
#      name: Heizung Skript zum Ausschalten
#      description: Das Skript, das die Heizung steuert
#      selector:
#        entity:
#          include_entities:
#          # Add your heater script entities here
#            - script.device_control_heater_off
    target_script_ac_on:
      name: Klima / Abluft Skript zum Einschalten
      description: Das Skript, das die Klima / Abluft steuert
      selector:
        entity:
          include_entities:
          # Add your ac script entities here
            - script.device_control_airflowfan_on
    target_script_ac_off:
      name: Klima / Abluft Skript zum Ausschalten
      description: Das Skript, das die Klima / Abluft steuert
      selector:
        entity:
          include_entities:
          # Add your ac script entities here
            - script.device_control_airflowfan_off


mode: single

trigger:
# Wenn der Zustand von temperature_trigger_low_adjustment von "off" auf "on" wechselt, wird die Automatisierung ausgelöst
#  - platform: state
#    entity_id: !input temperature_trigger_low_adjustment
#    from: "off"
#    to: "on"
#    id: "low_adjustment"
# Wenn der Zustand von temperature_trigger_low_fixed von "off" auf "on" wechselt, wird die Automatisierung ausgelöst

#  - platform: state
#    entity_id: !input temperature_trigger_low_fixed
#    from: "off"
#    to: "on"
#    id: "low_fixed"
# Wenn der Zustand von temperature_trigger_high_adjustment von "off" auf "on" wechselt, wird die Automatisierung ausgelöst

  - platform: state
    entity_id: !input temperature_trigger_high_adjustment
    from: "off"
    to: "on"
    id: "high_adjustment"
# Wenn der Zustand von temperature_trigger_high_fixed von "off" auf "on" wechselt, wird die Automatisierung ausgelöst
  - platform: state
    entity_id: !input temperature_trigger_high_fixed
    from: "off"
    to: "on"
    id: "high_fixed"

condition:
  # Die Automatisierung wird nur ausgeführt, wenn der Zustand von grow_stage_inputselector einen bestimmten Wert hat
  - condition: state
    entity_id: !input grow_stage_inputselector
    state: !input grow_stage_value

action:
#  - if:
#      - condition: trigger
#        id:
#          - "low_adjustment"
#    then:
#      - service: !input target_script_heater_on
#  - if:
#      - condition: trigger
#        id:
#          - "low_fixed"
#    then:
#      - service: !input target_script_heater_off
  - if:
      - condition: trigger
        id:
          - "high"
    then:
      - service: !input target_script_ac_on
  - if:
      - condition: trigger
        id:
          - "high_fixed"
    then:
      - service: !input target_script_ac_off
