blueprint:
  name: GrowBot automatic humidity control 
  description: >
    Die Datei auto_humidity.yaml ist Teil des GrowBot Open Source-Projekts und dient zur automatischen Steuerung der Luftfeuchtigkeit in Ihrer Grow-Umgebung. Sie enthält ein Blueprint für eine Home Assistant-Automation, die Sensoren für die aktuelle Luftfeuchtigkeit, minimale, ziel- und maximale Luftfeuchtigkeitswerte sowie den aktuellen Wachstumsstadium verwendet, um die Luftfeuchtigkeit optimal zu steuern.
    

    Sie können die Datei auto_humidity.yaml auf GitHub einsehen und herunterladen.
    
    
    Das GrowBot Open Source-Projekt ist ein gemeinnütziges Projekt, das sich auf die Bereitstellung von Open-Source-Software für die Automatisierung von Pflanzenwachstumsprozessen konzentriert. Wenn Sie das Projekt unterstützen möchten, können Sie eine finanzielle Spende leisten. Ihre Unterstützung hilft dem Projekt, weiter zu wachsen und den Quellcode kostenlos zur Verfügung zu stellen. Jede Spende, egal wie klein, ist sehr geschätzt und hilft uns, unsere Mission fortzusetzen. Vielen Dank für Ihre Unterstützung!
  domain: automation
  author: GrowBot Open Source
  input:
    humidity_sensor:
      name: Feuchtigkeitssensor
      description: Der Sensor für die aktuelle Luftfeuchtigkeit
      selector:
        entity:
          include_entities:
          # Add your humidity sensor entities here
            - sensor.airmonitoring_grow_humidity
    humidity_trigger_low_toFix:
      name: Min-Temperatur Trigger
      description: Der Trigger für die minimale Luftfeuchtigkeit
      selector:
        entity:
          domain: binary_sensor
          include_entities:
          # Add your humidity min trigger entities here
            - binary_sensor.humidity_low_toFix_seed
            - binary_sensor.humidity_low_toFix_veg
            - binary_sensor.humidity_low_toFix_flower
            - binary_sensor.humidity_low_toFix_dry 
    humidity_trigger_low_fixed:
      name: Min-Temperatur Trigger Fixiert
      description: Der Trigger für die minimale Luftfeuchtigkeit (fixiert)
      selector:
        entity:
          domain: binary_sensor
          include_entities:
          # Add your humidity min trigger entities here
            - binary_sensor.humidity_low_fixed_seed
            - binary_sensor.humidity_low_fixed_veg
            - binary_sensor.humidity_low_fixed_flower
            - binary_sensor.humidity_low_fixed_dry 
    humidity_trigger_high_toFix:
      name: Max-Temperatur Trigger
      description: Der Trigger für die maximale Luftfeuchtigkeit
      selector:
        entity:
          domain: binary_sensor
          include_entities:
          # Add your humidity max trigger entities here
            - binary_sensor.humidity_high_toFix_seed
            - binary_sensor.humidity_high_toFix_veg
            - binary_sensor.humidity_high_toFix_flower
            - binary_sensor.humidity_high_toFix_dry 
    humidity_trigger_high_fixed:
      name: Max-Temperatur Trigger fixiert
      description: Der Trigger für die maximale Luftfeuchtigkeit (fixiert)
      selector:
        entity:
          domain: binary_sensor
          include_entities:
          # Add your humidity max trigger entities here
            - binary_sensor.humidity_high_fixed_seed
            - binary_sensor.humidity_high_fixed_veg
            - binary_sensor.humidity_high_fixed_flower
            - binary_sensor.humidity_high_fixed_dry 
    grow_stage_inputselector:
      name: Pflanzenstadiums Auswahl
      description: Der Input-Selektor für das Wachstumsstadium
      selector:
        entity:
          include_entities:
          # Add your grow stage input selector entities here
            - input_select.plant1_stage
    grow_stage_value:
      name: Pflanzenstadiums Wert
      description: Der Wert für das Wachstumsstadium
      selector:
        select:
          options:
          # Add your grow stage values here
            - Seed
            - Veg
            - Flower
            - Dry
          mode: dropdown
    target_script_humidifier_on:
      name: Luftbefeuchter Skript zum Einschalten
      description: Das Skript, das den Luftbefeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your humidifier script entities here
            - script.device_control_humidifier_on
    target_script_humidifier_off:
      name: Luftbefeuchter Skript zum Ausschalten
      description: Das Skript, das den Luftbefeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your humidifier script entities here
            - script.device_control_humidifier_off
    target_script_dehumidifier_on:
      name: Luftentfeuchter Skript zum Einschalten
      description: Das Skript, das den Luftentfeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your dehumidifier script entities here
            - script.device_control_airflowfan_on
    target_script_dehumidifier_off:
      name: Luftentfeuchter Skript zum Ausschalten
      description: Das Skript, das den Luftentfeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your dehumidifier script entities here
            - script.device_control_airflowfan_off


mode: single

trigger:
  - platform: state
    entity_id: !input humidity_trigger_low_toFix
    from: "off"
    to: "on"
    id: "low_toFix"
  - platform: state
    entity_id: !input humidity_trigger_low_fixed
    from: "off"
    to: "on"
    id: "low_fixed"
  - platform: state
    entity_id: !input humidity_trigger_high_toFix
    from: "off"
    to: "on"
    id: "high_toFix"
  - platform: state
    entity_id: !input humidity_trigger_high_fixed
    from: "off"
    to: "on"
    id: "high_fixed"

condition:
  - condition: state
    entity_id: !input grow_stage_inputselector
    state: !input grow_stage_value

action:
  - if:
      - condition: trigger
        id:
          - "low_toFix"
    then:
      - service: !input target_script_humidifier_on
  - if:
      - condition: trigger
        id:
          - "low_fixed"
    then:
      - service: !input target_script_humidifier_off
  - if:
      - condition: trigger
        id:
          - "high"
    then:
      - service: !input target_script_dehumidifier_on
  - if:
      - condition: trigger
        id:
          - "high_fixed"
    then:
      - service: !input target_script_dehumidifier_off
