blueprint:
  name: GrowBot schedule controled light
  description: >
    This automation blueprint is used to control the light schedule based on the plant stage.
  domain: automation
  author: GrowBot Open Source
  input:
    light_schedule:
      name: Belichtungsplan
      selector:
        entity:
          include_entities:
            - schedule.lightschedule_flower
            - schedule.lightschedule_seed
            - schedule.lightschedule_veg
    grow_stage_inputselector:
      name: Pflanzenstadiums Eingangswähler
      selector:
        entity:
          include_entities:
            - input_select.plant1_stage
    grow_stage_value:
      name: Pflanzenstadiums Wert
      selector:
        select:
          options:
            - Seed
            - Veg
            - Flower
            - Dry
          mode: dropdown
    target_script_light_on:
      name: Licht Skript zum Einschalten
      description: Das Skript, das den Licht steuert
      selector:
        entity:
          include_entities:
          # Add your dehumidifier script entities here
            - script.device_control_light_on
    target_script_light_off:
      name: Licht Skript zum Einschalten
      description: Das Skript, das den Licht steuert
      selector:
        entity:
          include_entities:
          # Add your dehumidifier script entities here
            - script.device_control_light_off

mode: single

trigger:
  - platform: state
    entity_id: !input light_schedule
    id: "on"
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input light_schedule
    id: "off"
    from: "on"
    to: "off"
condition:
  - condition: state
    entity_id: !input grow_stage_inputselector
    state: !input grow_stage_value
    for:
      hours: 0
      minutes: 2
      seconds: 0
action:
  - if:
      - condition: trigger
        id:
          - "on"
    then:
      - service: !input target_script_light_on

    else:
      - service: !input target_script_light_off
