blueprint:
  name: GrowBot automatic humidity control
  description: ---- DESCRIPTION HERE -----
  domain: automation
  author: GrowBot Open Source
  input:
    humidity_sensor:
      name: Feuchtigkeitssensor
      selector:
        entity:
          include_entities:
            - sensor.airmonitoring_grow_humidity
    humidity_min_trigger:
      name: Min-Temperatur Trigger
      selector:
        entity:
          include_entities:
            - sensor.humidity_low_seed
            - sensor.humidity_low_veg
            - sensor.humidity_low_flower
            - sensor.humidity_low_dry 
    humidity_target_trigger:
      name: Ziel Temperatur Trigger
      selector:
        entity:
          include_entities:
            - sensor.humidity_good_seed
            - sensor.humidity_good_veg
            - sensor.humidity_good_flower
            - sensor.humidity_good_dry 
    humidity_max_trigger:
      name: Max-Temperatur Trigger
      selector:
        entity:
          include_entities:
            - sensor.humidity_high_seed
            - sensor.humidity_high_veg
            - sensor.humidity_high_flower
            - sensor.humidity_high_dry 
    grow_stage_inputselector:
      name: Pflanzenstadium Auswahl
      selector:
        entity:
          include_entities:
            - input_select.plant1_stage
    grow_stage_value:
      name: Pflanzenstadium
      selector:
        select:
          options:
            - Seed
            - Veg
            - Flower
            - Dry
          mode: dropdown
    target_script_humidifier:
      name: Luftbefeuchter
      selector:
        entity:
          include_entities:
            - script.humidifier_control
    target_script_dehumidifier:
      name: Luftentfeuchter
      selector:
        entity:
          include_entities:
            - script.airflowfan_control

mode: single

trigger:
  - platform: state
    entity_id: !input humidity_high_trigger
    to: "true"
    for:
      hours: 0
      minutes: 1
      seconds: 0
    id: "high"
  - platform: state
    entity_id: !input humidity_low_trigger
    to: "true"
    for:
      hours: 0
      minutes: 1
      seconds: 0
    id: "low"
  - platform: state
    entity_id: !input humidity_good_trigger
    to: "true"
    for:
      hours: 0
      minutes: 1
      seconds: 0
    id: "good"

condition:
  - condition: state
    entity_id: !input grow_stage_inputselector
    state: !input grow_stage_value
    for:
      hours: 0
      minutes: 2
      seconds: 0
action:
  - if:
      - condition: trigger
        id:
          - "low"
    then:
      - service: !input target_script_humidifier
        data:
          state: true
  - if:
      - condition: trigger
        id:
          - "high"
    then:
      - service: !input target_script_dehumidifier
        data:
          state: true
  - if:
      - condition: trigger
        id:
          - "good"
    then:
      - service: !input target_script_humidifier
        data:
          state: false
      - service: !input target_script_dehumidifier
        data:
          state: false
