blueprint:
  name: GrowBot automatic humidity control 
  description: >
    Die Datei auto_humidity.yaml ist Teil des GrowBot Open Source-Projekts und dient zur automatischen Steuerung der Luftfeuchtigkeit in Ihrer Grow-Umgebung. Sie enthält ein Blueprint für eine Home Assistant-Automation, die Sensoren für die aktuelle Luftfeuchtigkeit, minimale, ziel- und maximale Luftfeuchtigkeitswerte sowie den aktuellen Wachstumsstadium verwendet, um die Luftfeuchtigkeit optimal zu steuern.
    
    Sie können die Datei auto_humidity.yaml auf GitHub einsehen und herunterladen.
    
    Das GrowBot Open Source-Projekt ist ein gemeinnütziges Projekt, das sich auf die Bereitstellung von Open-Source-Software für die Automatisierung von Pflanzenwachstumsprozessen konzentriert. Wenn Sie das Projekt unterstützen möchten, können Sie eine finanzielle Spende leisten. Ihre Unterstützung hilft dem Projekt, weiter zu wachsen und den Quellcode kostenlos zur Verfügung zu stellen. Jede Spende, egal wie klein, ist sehr geschätzt und hilft uns, unsere Mission fortzusetzen. Vielen Dank für Ihre Unterstützung!
  domain: automation
  author: GrowBot Open Source
  input:
    humidity_sensor:
      name: Feuchtigkeitssensor
      description: Der Sensor für die aktuelle Luftfeuchtigkeit
      selector:
        entity:
          include_entities:
          # Add your humidity sensor entities here
            - sensor.airmonitoring_grow_humidity
    humidity_trigger_low:
      name: Min-Temperatur Trigger
      description: Der Trigger für die minimale Luftfeuchtigkeit
      selector:
        entity:
          domain: sensor
          include_entities:
          # Add your humidity min trigger entities here
            - sensor.humidity_low_seed
            - sensor.humidity_low_veg
            - sensor.humidity_low_flower
            - sensor.humidity_low_dry 
    humidity_trigger_target:
      name: Ziel-Temperatur Trigger
      description: Der Trigger für die Ziel-Luftfeuchtigkeit
      selector:
        entity:
          domain: sensor     
          include_entities:
        # Add your humidity target trigger entities here
            - sensor.humidity_good_seed
            - sensor.humidity_good_veg
            - sensor.humidity_good_flower
            - sensor.humidity_good_dry 
    humidity_trigger_high:
      name: Max-Temperatur Trigger
      description: Der Trigger für die maximale Luftfeuchtigkeit
      selector:
        entity:
          domain: sensor
          include_entities:
          # Add your humidity max trigger entities here
            - sensor.humidity_high_seed
            - sensor.humidity_high_veg
            - sensor.humidity_high_flower
            - sensor.humidity_high_dry 
    grow_stage_inputselector:
      name: Pflanzenstadiums Auswahl
      description: Der Input-Selektor für das Wachstumsstadium
      selector:
        entity:
          include_entities:
          # Add your grow stage input selector entities here
            - input_select.plant1_stage
    grow_stage_value:
      name: Pflanzenstadiums Wert
      description: Der Wert für das Wachstumsstadium
      selector:
        select:
          options:
          # Add your grow stage values here
            - Seed
            - Veg
            - Flower
            - Dry
          mode: dropdown
    target_script_humidifier:
      name: Luftbefeuchter Skript
      description: Das Skript, das den Luftbefeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your humidifier script entities here
            - script.humidifier_control
    target_script_dehumidifier:
      name: Luftentfeuchter Skript
      description: Das Skript, das den Luftentfeuchter steuert
      selector:
        entity:
          include_entities:
          # Add your dehumidifier script entities here
            - script.airflowfan_control

mode: single

trigger:
  - platform: state
    entity_id: !input humidity_trigger_high
    to: "True"
    for:
      hours: 0
      minutes: 1
      seconds: 0
    id: "high"
  - platform: state
    entity_id: !input humidity_trigger_low
    to: "True"
    for:
      hours: 0
      minutes: 1
      seconds: 0
    id: "low"
  - platform: state
    entity_id: !input humidity_trigger_target
    to: "True"
    id: "good"

condition:
  - condition: state
    entity_id: !input grow_stage_inputselector
    state: !input grow_stage_value
    for:
      hours: 0
      minutes: 2
      seconds: 0
action:
  - if:
      - condition: trigger
        id:
          - "low"
    then:
      - service: !input target_script_humidifier
        data:
          state: true
  - if:
      - condition: trigger
        id:
          - "high"
    then:
      - service: !input target_script_dehumidifier
        data:
          state: true
  - if:
      - condition: trigger
        id:
          - "good"
    then:
      - service: !input target_script_humidifier
        data:
          state: false
      - service: !input target_script_dehumidifier
        data:
          state: false
